### ISSUE TITLE
MHWRender has not been declared

### ISSUE THREAD

**Issue by gshankar165** [LumaPictures/openvdb-render#2]
[ 55%] Built target vdbVisualizerWriter
[ 59%] Building CXX object plugin/CMakeFiles/openvdb_render.dir/main.cpp.o
[ 62%] Building CXX object plugin/CMakeFiles/openvdb_render.dir/vdb_sliced_display.cpp.o
[ 66%] Building CXX object plugin/CMakeFiles/openvdb_render.dir/vdb_subscene_override.cpp.o
In file included from /root/Documents/openvdb-render-master/plugin/vdb_sliced_display.cpp:1:0:
/root/Documents/openvdb-render-master/plugin/vdb_sliced_display.h:60:31: error: ‘MHWRender’ has not been declared
     explicit VDBSlicedDisplay(MHWRender::MPxSubSceneOverride& parent);
                               ^
/root/Documents/openvdb-render-master/plugin/vdb_sliced_display.h:60:61: error: expected ‘)’ before ‘&’ token
     explicit VDBSlicedDisplay(MHWRender::MPxSubSceneOverride& parent);
                                                             ^
/root/Documents/openvdb-render-master/plugin/vdb_sliced_display.h:67:9: error: ‘MHWRender’ has not been declared
         MHWRender::MSubSceneContainer& container,
         ^
/root/Documents/openvdb-render-master/plugin/vdb_sliced_display.h:67:38: error: expected ‘,’ or ‘...’ before ‘&’ token
         MHWRender::MSubSceneContainer& container,
                                      ^
/root/Documents/openvdb-render-master/plugin/vdb_sliced_display.h:72:33: error: ‘MMatrixArray’ does not name a type
     void setWorldMatrices(const MMatrixArray& world_matrices);
                                 ^
/root/Documents/openvdb-render-master/plugin/vdb_sliced_display.h:72:47: error: ISO C++ forbids declaration of ‘world_matrices’ with no type [-fpermissive]
     void setWorldMatrices(const MMatrixArray& world_matrices);
                                               ^
/root/Documents/openvdb-render-master/plugin/vdb_sliced_display.cpp:747:11: error: ‘MSamplerState’ does not name a type
     const MSamplerState& getSamplerState() const { return *m_ramp_sampler_state; }
           ^
/root/Documents/openvdb-render-master/plugin/vdb_sliced_display.cpp: In static member function ‘static void VolumeShader::preDrawCallback(MHWRender::MDrawContext&, const MHWRender::MRenderItemList&, MHWRender::MShaderInstance*)’:
/root/Documents/openvdb-render-master/plugin/vdb_sliced_display.cpp:1650:38: error: ‘MRasterizerState’ has not been declared
         raster_state_desc.cullMode = MRasterizerState::kCullNone;
                                      ^
/root/Documents/openvdb-render-master/plugin/vdb_sliced_display.cpp: In constructor ‘VDBSlicedDisplayImpl::VDBSlicedDisplayImpl(MHWRender::MPxSubSceneOverride&)’:
/root/Documents/openvdb-render-master/plugin/vdb_sliced_display.cpp:1895:75: error: ‘class FloatRampTexture’ has no member named ‘getSamplerState’
     (m_volume_shader->setParameter("density_ramp_sampler", m_density_ramp.getSamplerState()));
                                                                           ^
/root/Documents/openvdb-render-master/plugin/vdb_sliced_display.cpp:1896:81: error: ‘class RGBRampTexture’ has no member named ‘getSamplerState’
     (m_volume_shader->setParameter("scattering_ramp_sampler", m_scattering_ramp.getSamplerState()));
                                                                                 ^
/root/Documents/openvdb-render-master/plugin/vdb_sliced_display.cpp:1897:77: error: ‘class RGBRampTexture’ has no member named ‘getSamplerState’
     (m_volume_shader->setParameter("emission_ramp_sampler", m_emission_ramp.getSamplerState()));
                                                                             ^
In file included from /usr/autodesk/maya2017/include/maya/MPxSurfaceShape.h:22:0,
                 from /root/Documents/openvdb-render-master/plugin/vdb_visualizer.h:3,
                 from /root/Documents/openvdb-render-master/plugin/vdb_sliced_display.h:3,
                 from /root/Documents/openvdb-render-master/plugin/vdb_sliced_display.cpp:1:
/root/Documents/openvdb-render-master/plugin/vdb_sliced_display.cpp:1900:94: error: ‘class RGBRampTexture’ has no member named ‘getSamplerState’
     CHECK_MSTATUS(m_volume_shader->setParameter("blackbody_lut_sampler", m_blackbody_lut.lut.getSamplerState()));
                                                                                              ^
/usr/autodesk/maya2017/include/maya/MStatus.h:176:26: note: in definition of macro ‘CHECK_MSTATUS’
  MStatus _maya_status = (_status);     \
                          ^
/root/Documents/openvdb-render-master/plugin/vdb_sliced_display.cpp: At global scope:
/root/Documents/openvdb-render-master/plugin/vdb_sliced_display.cpp:2222:1: error: prototype for ‘VDBSlicedDisplay::VDBSlicedDisplay(MHWRender::MPxSubSceneOverride&)’ does not match any in class ‘VDBSlicedDisplay’
 VDBSlicedDisplay::VDBSlicedDisplay(MHWRender::MPxSubSceneOverride& parent)
 ^
In file included from /root/Documents/openvdb-render-master/plugin/vdb_sliced_display.cpp:1:0:
/root/Documents/openvdb-render-master/plugin/vdb_sliced_display.h:62:5: error: candidates are: VDBSlicedDisplay::VDBSlicedDisplay(VDBSlicedDisplay&&)
     VDBSlicedDisplay(VDBSlicedDisplay&&) = delete;
     ^
/root/Documents/openvdb-render-master/plugin/vdb_sliced_display.h:61:5: error:                 VDBSlicedDisplay::VDBSlicedDisplay(const VDBSlicedDisplay&)
     VDBSlicedDisplay(const VDBSlicedDisplay&) = delete;
     ^
/root/Documents/openvdb-render-master/plugin/vdb_sliced_display.cpp:2231:6: error: prototype for ‘bool VDBSlicedDisplay::update(MHWRender::MSubSceneContainer&, const openvdb::v5_1::io::File*, const MBoundingBox&, const VDBSlicedDisplayData&, VDBSlicedDisplayChangeSet&)’ does not match any in class ‘VDBSlicedDisplay’
 bool VDBSlicedDisplay::update(
      ^
In file included from /root/Documents/openvdb-render-master/plugin/vdb_sliced_display.cpp:1:0:
/root/Documents/openvdb-render-master/plugin/vdb_sliced_display.h:66:10: error: candidate is: bool VDBSlicedDisplay::update(int)
     bool update(
          ^
/root/Documents/openvdb-render-master/plugin/vdb_sliced_display.cpp:2241:6: error: prototype for ‘void VDBSlicedDisplay::setWorldMatrices(const MMatrixArray&)’ does not match any in class ‘VDBSlicedDisplay’
 void VDBSlicedDisplay::setWorldMatrices(const MMatrixArray& world_matrices)
      ^
In file included from /root/Documents/openvdb-render-master/plugin/vdb_sliced_display.cpp:1:0:
/root/Documents/openvdb-render-master/plugin/vdb_sliced_display.h:72:10: error: candidate is: void VDBSlicedDisplay::setWorldMatrices(const int&)
     void setWorldMatrices(const MMatrixArray& world_matrices);
          ^
make[2]: *** [plugin/CMakeFiles/openvdb_render.dir/vdb_sliced_display.cpp.o] Error 1
make[1]: *** [plugin/CMakeFiles/openvdb_render.dir/all] Error 2
make: *** [all] Error 2

**Comment by sirpalee** [comment]
Hey, we missed this issue completely. I'm going to close it down. If you are still interested in fixing the issue, please try the latest version and open a new issue.
